bsp: u-boot: Fix C flags generation for MUL=2
MUL64 wasn't supported by BSP that's why it generated
settings without multiplier.

It caused problem in u-boot compilation:
.../libgcc.a(_muldi3.o): In function `__muldi3':
.../gcc-4.1.2/gcc/libgcc2.c:533: undefined reference to `_GLOBAL_OFFSET_TABLE_'

Also add missing flags for others.

Signed-off-by: Michal Simek <michal.simek@petalogix.com>